<a href="https://colab.research.google.com/github/GabrielVieiraDL/generation/blob/main/timestamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df_logs = pd.read_csv('/content/logs_seguranca_aula.csv')

display(df_logs.head(10))

# Sempre que temos um "timestamp" devemos verificar se ele é um timestamp
df_logs['timestamp'] = pd.to_datetime(df_logs['timestamp'])
df_logs.info()
df_logs.describe()

In [17]:
# Descobrir logins realizados fora do horário comercial
# seg - sex - 08 - 17

# o python pode identificar dentro de um timestamp valores ramificados
df_logs['hora'] = df_logs['timestamp'].dt.hour
df_logs['minutos'] = df_logs['timestamp'].dt.minute
df_logs['dia_semana'] = df_logs['timestamp'].dt.day_of_week
df_logs['nome_dia'] = df_logs['timestamp'].dt.day_name()

# Criar os filtros
# Fora do horário comercial das 00h até as 07h e das 17h até as 23h
display(df_logs[df_logs['hora'] != 8])

# Vamos exibir os dados que não são resource financeiro ou system

# or -----> dentro de if, for ou while
# | ------> operador de OU
# and -----> dentro de if, for ou while
# & -------> operador de E

display(df_logs[(df_logs['resource'] != 'financeiro') & (df_logs['resource'] != 'system')])

# filtrar colunas diferentes
# Somente falhas na sexta-feira

display(df_logs[(df_logs['status'] == "FAILED") & (df_logs['dia_semana'] == 6)])

# Encontrar informações que iniciam ou finalizam com
# startswith - é inicia com
# endswith - finaliza com
# mostrar tudo que termina com .csv

display(df_logs[df_logs['resource'].str.endswith(".csv", na=False)])

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_semana,nome_dia
1,2026-08-01 17:02:00,joao,200.100.10.5,LOGOUT,SUCCESS,dashboard,0,17,2,5,Saturday
2,2026-08-01 17:05:00,maria,200.100.10.12,LOGIN,SUCCESS,financeiro,0,17,5,5,Saturday
3,2026-08-02 00:00:15,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,1,0,0,6,Sunday
4,2026-08-02 00:01:10,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,2,0,1,6,Sunday
5,2026-08-02 00:03:45,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,244,0,3,6,Sunday
6,2026-08-02 00:04:50,joao,189.45.12.99,LOGIN,SUCCESS,system,245,0,4,6,Sunday
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6,Sunday
8,2026-08-02 00:06:01,joao,189.45.12.99,ACCESS_FILE,SUCCESS,helpdesk_tickets,0,0,6,6,Sunday
9,2026-08-02 00:07:30,joao,189.45.12.99,UPLOAD_FILE,SUCCESS,Helpdesk-NEW-VERSION.exe,0,0,7,6,Sunday

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_semana,nome_dia
0,2026-08-01 08:58:00,joao,200.100.10.5,LOGIN,SUCCESS,dashboard,0,8,58,5,Saturday
1,2026-08-01 17:02:00,joao,200.100.10.5,LOGOUT,SUCCESS,dashboard,0,17,2,5,Saturday
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6,Sunday
8,2026-08-02 00:06:01,joao,189.45.12.99,ACCESS_FILE,SUCCESS,helpdesk_tickets,0,0,6,6,Sunday
9,2026-08-02 00:07:30,joao,189.45.12.99,UPLOAD_FILE,SUCCESS,Helpdesk-NEW-VERSION.exe,0,0,7,6,Sunday

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_semana,nome_dia
3,2026-08-02 00:00:15,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,1,0,0,6,Sunday
4,2026-08-02 00:01:10,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,2,0,1,6,Sunday
5,2026-08-02 00:03:45,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,244,0,3,6,Sunday
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6,Sunday

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_semana,nome_dia
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6,Sunday